<?php


namespace App\Register;


use App\Model\Database;
use PDOException;

class Register extends Database
{
    public function __construct()
    {
        parent::__construct();
    }

    public function Update($query)
    {
        return parent::delete_Update_Store($query); // TODO: Change the autogenerated stub
    }


}