<?php


namespace App\Apply;


use App\Message\Message;
use App\Model\Database;
use Exception;

class Apply extends Database
{
    private $studentID, $applyDate, $applyID, $progress, $reason;

    public function __construct()
    {
        parent::__construct();
    }

    public function initVar($postArray)
    {
        if (array_key_exists('studentID', $postArray))
            $this->studentID = $postArray['studentID'];

        if (array_key_exists('applyDate', $postArray))
            $this->applyDate = $postArray['applyDate'];
    }

    public function store()
    {
        $query = "INSERT INTO `apply` (`student_id`, `apply_date`) VALUES (?,?)";
        $dataArray = [$this->studentID, $this->applyDate];

        try {

            $delete = "DELETE FROM `apply` WHERE apply.student_id = '$this->studentID' and progress=0";
            $this->delete_Update_Store($delete);
            $statement = $this->dbconnection->prepare($query); // return a boolean value
            $status = $statement->execute($dataArray); // return a boolean value
            $this->storeToAdministration();
            if ($status) {
                return true;
            } else {
                Message::message("Failed! Not Applied.<br>");
                return false;
            }

        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }

    private function storeToAdministration()
    {
        $query = 'INSERT INTO `administrator` (`apply_id`) VALUES((SELECT a.apply_id FROM apply a WHERE student_id=? and a.progress=1))';
        $dataArray = [$this->studentID];
        try {
            $statement = $this->dbconnection->prepare($query); // return a boolean value
            $status = $statement->execute($dataArray); // return a boolean value

            if ($status) {
                return true;
            } else {
                Message::message("Failed! Not Applied.<br>");
                return false;
            }

        } catch (Exception $e) {
            echo $e->getMessage();
        }

    }

    public function ifOnWay()
    {
        $query = "SELECT * FROM `apply` WHERE apply.student_id = '$this->studentID'";
        try {
            $statement = $this->dbconnection->prepare($query); // return a boolean value
            $statement->execute(); // return a boolean value
            $data = $statement->fetch();

            if ($data['progress'] == 0) {
                return false;
            } else {
                return true;
            }

        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }

    public function delete_Update_Store($query)
    {
        return parent::delete_Update_Store($query); // TODO: Change the autogenerated stub
    }

}